name: memora
description: "Memora is a Flutter application designed to help users track their daily activities, providing insights into their productivity and well-being."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  http: ^1.4.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  timezone: ^0.10.1
  scrollable_positioned_list: ^0.3.8
  flutter_native_splash: ^2.4.0
  markdown_widget: ^2.3.2+8
  flutter_heatmap_calendar: ^1.0.5
  uuid: ^4.4.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^7.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "#42a5f5"
  color_dark: "#000000"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/proficiency_levels/
# This is a comment to force re-analysis