name: memora
description: "Your Smart Learning Partner That Turns Notion Notes into AI-Powered Quizzes"

version: 1.0.2+4
environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  http: ^1.4.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  timezone: ^0.10.1
  scrollable_positioned_list: ^0.3.8
  flutter_native_splash: ^2.4.0
  markdown_widget: ^2.3.2+8
  flutter_heatmap_calendar: ^1.0.5
  uuid: ^4.4.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  google_sign_in: ^7.1.1
  go_router: ^16.1.0
  firebase_messaging: ^16.0.0
  flutter_colorpicker: ^1.1.0
  share_plus: ^11.0.0
  google_generative_ai: ^0.4.7
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_light.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter_native_splash:
  color: "#42a5f5"
  color_dark: "#000000"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/login/
    - assets/images/proficiency_levels/